name: Maven Verify
on: [push,pull_request]
jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up JDK
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'adopt'
          java-version: '16'
          cache: 'maven'

      - name: Maven Verify
        run: mvn -B clean install
