name: Packaging

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:

  push_container_images_to_registries:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      DOCKER_BUILDKIT: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Retrieve branch or tag name
        id: refvar
        run: echo "::set-output name=gitRefName::${GITHUB_REF#refs/*/}"
      
      - name: Build local Container Image for scanning
        run: |
          mvn compile jib:dockerBuild \
            -Djib.to.image="com.cosmotech/azure-storage-simulator-connector:${GITHUB_SHA}"

      - name: Scan Container Image
        id: scan
        # TODO For now, do not block if the container scan action returns issues
        continue-on-error: true
        uses: Azure/container-scan@v0.1
        with:
          image-name: com.cosmotech/azure-storage-simulator-connector:${{ github.sha }}

      - name: Archive container image scan report
        if: ${{ always() }}
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: container-image-scan-report
          path: ${{ steps.scan.outputs.scan-report-path }}
          retention-days: 3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push API Container Image (tag) to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker image tag com.cosmotech/azure-storage-simulator-connector:${GITHUB_SHA} \
            ghcr.io/cosmo-tech/azure-storage-simulator-connector:${{ steps.refvar.outputs.gitRefName }}
          docker image push ghcr.io/cosmo-tech/azure-storage-simulator-connector:${{ steps.refvar.outputs.gitRefName }}

      - name: Push API Container Image (latest) to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: |
          docker image tag com.cosmotech/azure-storage-simulator-connector:${GITHUB_SHA} \
            ghcr.io/cosmo-tech/azure-storage-simulator-connector:latest
          docker image push ghcr.io/cosmo-tech/azure-storage-simulator-connector:latest
